# Generated by Django 4.1.1 on 2022-10-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_itemorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rfid',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
