# Generated by Django 4.1.1 on 2022-10-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_rfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
