# Generated by Django 4.1.1 on 2022-10-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_itemorder_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='FINALIZADO', max_length=10),
            preserve_default=False,
        ),
    ]
